theme="catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true

[editor.lsp]
display-messages = true
display-inlay-hints = true

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
